image: python:3.8.12
test:
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - python manage.py migrate
        - python manage.py collectstatic --no-input
        - coverage run --source='.' manage.py test

    coverage: '/TOTAL.*\s+(\d+%)$/'

staging:
    stage: deploy
    image: ruby:latest
    before_script:
        - gem install dpl
        - gem install faraday -v 1.8.0
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --run='python manage.py migrate'
